#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: optitrack/calibrator/pose
        position: optitrack/calibrator/position
        child_frame_id: optitrack/calibrator/base_link
        parent_frame_id: optitrack_frame
        use_new_coordinates: false
    '2':
        pose: optitrack/basket/pose
        position: optitrack/ball/position
        child_frame_id: optitrack/ball/base_link
        parent_frame_id: optitrack_frame
        use_new_coordinates: false
optitrack_config:
        multicast_address: 224.0.0.1
